# snakejob -j 1000 --max-jobs-per-second 1 --keep-going --notemp
# snakemake --max-jobs-per-second 1 --keep-going --notemp

from datetime import date
today_date = date.today()
# shell.prefix('module load plink/1.90 R/3.6.3; ')
shell.prefix('module load plink/1.90 R/3.6.3; ')

# subworkflow test:
#     workdir:
#         "../"
#     snakefile:
#         "rules/mr.smk"
#     configfile:
#         "config/config_mr_test.yaml"

# snakemake -s workflow/rules/mr.smk --configfile config/config_covid.yaml -j 1 --use-conda --keep-going --notemp
subworkflow mr_covid:
    workdir:
        "../"
    snakefile:
        "rules/mr.smk"
    configfile:
        "config/config_covid.yaml"

# snakemake -s workflow/rules/mr.smk --configfile config/config_covid_eur.yaml -j 1 --use-conda --keep-going --notemp
subworkflow mr_covideur:
    workdir:
        "../"
    snakefile:
        "rules/mr.smk"
    configfile:
        "config/config_covid.yaml"

# snakemake -s workflow/rules/mr.smk --configfile config/config_covid_eur_wo_ukbb.yaml -j 1 --use-conda --keep-going --notemp
subworkflow mr_covideurwoukbb:
    workdir:
        "../"
    snakefile:
        "rules/mr.smk"
    configfile:
        "config/config_covid.yaml"

rule all:
    input:
        # test(expand("results/test/All/test_MR_Analaysis_{DATE}.html", DATE = today_date)),
        mr_covid(expand("results/MRcovid/All/MRcovid_MR_Analaysis_{DATE}.html", DATE = today_date)),
        mr_covideur(expand("results/MRcovideur/AllMRcovideur_MR_Analaysis_{DATE}.html", DATE = today_date)),
        mr_covideurwoukbb(expand("results/MRcovideurwoukbb/All/MRcovideurwoukbb_MR_Analaysis_{DATE}.html", DATE = today_date)),
