---
title: "MR Results"
author: "Shea Andrews"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    keep_md: true
    toc: true
    number_sections: false
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: false
params:
  MR_results.path: NA
  MRdat.path: NA
  mrpresso_global.path: NA
  mrpresso_global_wo_outliers.path: NA
  egger_comb.path: NA
  power.path: NA
  steiger.path: NA
  output.path: NA
  model: NA
  rwd: NA
  DATE: NA
  rlib: NA
  exposures: NA
  outcomes: NA
editor_options:
  chunk_output_type: console
---

```{r setup, echo=FALSE, message = FALSE, warning = FALSE}
message("Setup \n")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = params$rwd)

if(any(grepl("conda", .libPaths(), fixed = TRUE))){
  message("Setting libPaths")
  df = .libPaths()
  conda_i = which(grepl("conda", df, fixed = TRUE))
  .libPaths(c(df[conda_i], df[-conda_i]))
}

library(tidyverse)
library(glue)
library(TwoSampleMR)
library(gridExtra)
library(ggallin)
library(ggpubr)
library(qvalue)
library(here)
source(here("workflow", "scripts", "miscfunctions.R"), chdir = TRUE)
```

```{r sandbox, eval=F}
# model <- "MRcovideurwoukbb"
model <- "MRcovideur"
# DATE = Sys.Date() %>% str_replace_all(., '[[:punct:]]', "")
DATE = "20210224"
rwd = "/sc/arion/projects/LOAD/shea/Projects/MRcovid"
setwd(rwd)

MR_results.path = glue("results/{model}/All/{DATE}/MRresults.txt")
MRdat.path = glue("results/{model}/All/{DATE}/mrpresso_MRdat.csv")
mrpresso_res.path = glue("results/{model}/All/{DATE}/res_mrpresso.txt")
mrpresso_global.path = glue("results/{model}/All/{DATE}/global_mrpresso.txt")
mrpresso_global_wo_outliers.path = glue("results/{model}/All/{DATE}/global_mrpresso_wo_outliers.txt")
egger_comb.path = glue("results/{model}/All/{DATE}/pleiotropy.txt")
power.path = glue("results/{model}/All/{DATE}/power.txt")
steiger.path = glue("results/{model}/All/{DATE}/steiger.txt")
rg.path <- glue("results/RGcovid/ldsc/{DATE}/all_results_ldsc.tsv")

exposures = c('Yengo2018bmi', 'Mahajan2018t2d', 'Willer2013hdl', 'Willer2013ldl', 'Willer2013tc', 'Willer2013tg', 'Dashti2019slepdur', 'Evangelou2018dbp', 'Evangelou2018sbp', 'Evangelou2018pp', 'Howard2018dep', 'Jansen2018insom', 'Liu2019smkint', 'Liu2019smkcpd', 'Kunkle2019load', 'Revez2020vit250hd', 'Okada2014rartis', 'Nalls2019pd', 'Nicolas2018als', 'Ligthart2018crp', 'Wood2014height', 'Betham2015lupus', 'Patsopoulos2019multscler', 'Malik2018ais', 'Wuttke2019egfr', 'Wuttke2019ckd', 'Nikpay2015cad', 'Shah2020heartfailure', 'Olafsdottir2020asthma', 'Allen2020ipf', 'Linner2019risk', 'Demontis2018adhd', 'Grove2019asd', 'Ripke2014scz', 'Stahl2019bip', 'Astel2016rbc', 'Astel2016wbc', 'Astel2016plt')

if(model == "MRcovideur"){
  outcomes = c("covidhgi2020A2v5alleur", "covidhgi2020B2v5alleur", "covidhgi2020C2v5alleur")
} else if(model == "MRcovideurwoukbb"){
  outcomes = c("covidhgi2020A2v5alleurLeaveUKBB", "covidhgi2020B2v5alleurLeaveUKBB", "covidhgi2020C2v5alleurLeaveUKBB")
}

```

```{r snakemake-input}
model = params$model
rwd = params$rwd
DATE = params$DATE
MR_results.path = params$MR_results.path
MRdat.path = params$MRdat.path
mrpresso_global.path = params$mrpresso_global.path
mrpresso_global_wo_outliers.path = params$mrpresso_global_wo_outliers.path
egger_comb.path = params$egger_comb.path
power.path = params$power.path
steiger.path = params$steiger.path
output.path = params$outfile
exposures = params$exposures
outcomes = params$outcomes
```


```{r load-data}
##  Read in R datasets
## Outcomes to include the results

message(glue("\n Exposure - Outcome Pairs"))
source(here("workflow", "scripts", "traits.R"), chdir = TRUE)
exposures_outcomes <- expand_grid(exposures, outcomes) %>%
  magrittr::set_colnames(c("exposures.name", "outcomes.name")) %>%
  left_join(select(samplesize, code, trait, domain), by = c('exposures.name' = 'code')) %>%
  rename(exposure.name = trait, domain.exposure = domain) %>%
  left_join(select(samplesize, code, trait, domain), by = c('outcomes.name' = 'code')) %>%
  rename(outcome.name = trait, domain.outcome = domain) %>%
  mutate(domain.exposure = str_replace(domain.exposure, "Diagnosis", "Disease liability"),
         domain.exposure = str_replace(domain.exposure, "Neurpsychatric", "Neuropsychiatric"))

## Phenotype descriptions
a2_pheno <- distinct(exposures_outcomes, outcome.name) %>% filter(str_detect(outcome.name, 'A2')) %>% pull(outcome.name)
b2_pheno <- distinct(exposures_outcomes, outcome.name) %>% filter(str_detect(outcome.name, 'B2')) %>% pull(outcome.name)
c2_pheno <- distinct(exposures_outcomes, outcome.name) %>% filter(str_detect(outcome.name, 'C2')) %>% pull(outcome.name)

a2_pheno_id <- distinct(exposures_outcomes, outcomes.name) %>% filter(str_detect(outcomes.name, 'A2')) %>% pull(outcomes.name)
b2_pheno_id <- distinct(exposures_outcomes, outcomes.name) %>% filter(str_detect(outcomes.name, 'B2')) %>% pull(outcomes.name)
c2_pheno_id <- distinct(exposures_outcomes, outcomes.name) %>% filter(str_detect(outcomes.name, 'C2')) %>% pull(outcomes.name)

## Files
message(glue("\n Loading: ", MR_results.path))
MR_results <- read_tsv(MR_results.path) %>%
  filter(exposure %in% exposures, outcome %in% outcomes)

message(glue("\n Loading: ", MRdat.path))
MRdat.raw <- read_csv(MRdat.path, guess_max = 100000) %>%
  filter(exposure %in% exposures, outcome %in% outcomes)

message(glue("\n Loading: ", mrpresso_global.path))
mrpresso_global <- read_tsv(mrpresso_global.path) %>%
  filter(exposure %in% exposures, outcome %in% outcomes) %>%
  mutate(pval = as.character(pval))

message(glue("\n Loading: ", mrpresso_global_wo_outliers.path))
mrpresso_global_wo_outliers <- read_tsv(mrpresso_global_wo_outliers.path) %>%
  filter(exposure %in% exposures, outcome %in% outcomes) %>%
  mutate(pval = as.character(pval))

mrpresso_global_comb <- bind_rows(mrpresso_global, mrpresso_global_wo_outliers)

message(glue("\n Loading: ", mrpresso_res.path))
mrpresso_res <- read_tsv(mrpresso_res.path) %>%
  filter(exposure %in% exposures, outcome %in% outcomes) %>%
  mutate(outliers_removed = str_replace(outliers_removed, "Outlier-", ""),
         method = str_replace(method, "-", ""),
         method = paste(method, outliers_removed, sep = "_"),
         outliers_removed = FALSE) %>%
  rename(se = sd, MR.pval = pval) %>%
  select(-t.stat) %>%
  group_by(outcome, exposure) %>%
  mutate(n_outliers = max(nsnp) - min(nsnp),
         nsnp = max(nsnp)) %>%
  ungroup()

message(glue("\n Loading: ", egger_comb.path))
egger_comb <- read_tsv(egger_comb.path) %>%
  rename(egger_se = se) %>%
    filter(exposure %in% exposures, outcome %in% outcomes)

message(glue("\n Loading: ", steiger.path))
steiger <- read_tsv(steiger.path) %>%
  filter(exposure %in% exposures, outcome %in% outcomes)

message(glue("\n Loading: ", power.path))
power <- read_tsv(power.path) %>%
  filter(exposure %in% exposures, outcome %in% outcomes) %>%
  select(exposure, outcome, pt, outliers_removed, pve.exposure, F, Power) %>%
  mutate(pve.exposure = round(pve.exposure*100, 2),
         F = round(F, 2),
         Power = round(Power, 2))

rg.raw <- read_tsv(rg.path) %>%
  rename(se_rg = se, rg.p = p) %>%
  mutate(rg.lci = rg - (1.96 * se_rg),
         rg.uci = rg + (1.96 * se_rg),
         p1 = str_replace(p1, "\\.sumstats.gz", ""),
         p1 = str_replace(p1, "data/formated/ldsc/", ""),
         p2 = str_replace(p2, "data/formated/ldsc/", ""),
         p2 = str_replace(p2, ".sumstats.gz", ""))

rg <- rg.raw  %>%
  filter(p1 %in% exposures) %>%
  filter(p2 %in% outcomes) %>%
  mutate(rg.fdr = p.adjust(rg.p, "fdr")) %>%
  arrange(p2, rg.fdr)  %>%
  left_join(select(exposures_outcomes, exposures.name, outcomes.name, exposure.name, outcome.name),
            by = c("p1" = "exposures.name", "p2" = "outcomes.name"))

rg_covid <- rg.raw %>%
  filter(p1 %in% outcomes) %>%
  filter(p2 %in% outcomes) %>%
  mutate(rg.fdr = p.adjust(rg.p, "fdr")) %>%
  arrange(p2, rg.fdr) %>%
  mutate(outcome.name = fct_recode(p2,
                                   "Critical illness" = a2_pheno_id,
                                   Hospitalisation = b2_pheno_id,
                                   "Reported infection" = c2_pheno_id), 
         exposure.name = fct_recode(p1,
                                   "Critical illness" = a2_pheno_id,
                                   Hospitalisation = b2_pheno_id,
                                   "Reported infection" = c2_pheno_id))

```

## Genetic Correlations

```{r}
rg %>%
  select(p1, p2, exposure.name, nsnps, rg, se_rg, rg.p, rg.fdr, everything()) %>%
  mutate(rg.fdr = round_sci(rg.fdr),
         rg.p = round_sci(rg.p),
         rg = signif(rg, 2),
         se_rg = signif(se_rg, 2),
        ) %>%
write_csv(., glue("docs/{DATE}/{model}_LDSC_rgRes.csv"))

rg_covid %>%
  select(p1, p2, nsnps, rg, se_rg, rg.lci, rg.uci, z, rg.p)
```

## Harmonized exposure-outcome SNP dataset

```{r merge-data}
MRdat <- MRdat.raw  %>%
  ## Merge Sample Size information
  select(-samplesize.outcome, -samplesize.exposure) %>%
  left_join(select(samplesize, -pmid), by = c('exposure' = 'code')) %>%
  rename(samplesize.exposure = samplesize,
         ncase.exposure = ncase,
         ncontrol.exposure = ncontrol,
         logistic.exposure = logistic,
         exposure.name = trait,
         domain.exposure = domain,
         prevelance.exposure = prevelance) %>%
  left_join(select(samplesize, -pmid), by = c('outcome' = 'code')) %>%
  rename(samplesize.outcome = samplesize,
         ncase.outcome = ncase,
         ncontrol.outcome = ncontrol,
         logistic.outcome = logistic,
         outcome.name = trait,
         domain.outcome = domain,
         prevelance.outcome = prevelance)

```

```{r write-harmonized-data, echo=FALSE, eval=TRUE}
write_csv(MRdat, glue("docs/{DATE}/{model}_HarmonizedDatasets.csv"))
```


## MR Resuts

```{r mrsummary}

MRsummary <- MR_results %>%
  mutate(method = str_replace(method, "Inverse variance weighted \\(fixed effects\\)", 'IVW'),
         method = str_replace(method, "MR Egger", 'Egger'),
         method = str_replace(method, "Weighted median", 'WME'),
         method = str_replace(method, "Weighted mode", 'WMBE')) %>%
  rename(MR.pval = pval) %>%
  ## Join MR-PRESSO Results
  bind_rows(mrpresso_res) %>%
  ## Join MR-PRESSO Global results
  left_join(select(mrpresso_global_comb, outcome, exposure, pt, RSSobs, pval, outliers_removed),
            by = c('outcome', 'exposure', 'pt', 'outliers_removed')) %>%
  rename(MRPRESSO.pval = pval) %>%
  ## Join Egger Intercept results
  left_join(select(egger_comb, outcome, exposure, pt, Isq, egger_intercept, egger_se, pval, outliers_removed),
            by = c('outcome', 'exposure', 'pt', 'outliers_removed')) %>%
  rename(Egger.pval = pval) %>%
  select(outcome, exposure, pt, method, outliers_removed, nsnp, n_outliers, b, se, MR.pval,
         RSSobs, MRPRESSO.pval, egger_intercept, egger_se, Egger.pval, Isq) %>%
  arrange(outcome, exposure, pt, method, outliers_removed) %>%
  ## Join Steiger
  left_join(select(steiger, outcome, exposure, pt, outliers_removed,
                   snp_r2.exposure, snp_r2.outcome, correct_causal_direction, steiger_pval),
          by = c('outcome', 'exposure', 'pt', 'outliers_removed')) %>%
  left_join(select(power, outcome, exposure, pt, outliers_removed, F)) %>%
  ## Merge Sample Size information
  left_join(select(samplesize, code, trait, domain), by = c('exposure' = 'code')) %>%
  rename(exposure.name = trait,
         exposure.domain = domain) %>%
  left_join(select(samplesize, code, trait, domain), by = c('outcome' = 'code')) %>%
  rename(outcome.name = trait,
         outcome.domain = domain)

```

```{r, eval=TRUE}
write_csv(MRsummary, glue("docs/{DATE}/{model}_MRsummary.csv"))
```

```{r spread-res}
## Spread by methods
mrresults.methods <- MRsummary %>%
  filter(outliers_removed == FALSE) %>%
  generate_odds_ratios(.) %>%
  select(-lo_ci, -up_ci) %>%
  mutate(b = signif(b, 2),
         se = signif(se, 2),
         or = signif(or, 2),
         or_lci95 = signif(or_lci95, 2),
         or_uci95 = signif(or_uci95, 2),
         MR.pval = signif(MR.pval, 2),
         RSSobs = round(RSSobs, 1),
         egger_intercept = signif(egger_intercept, 3),
         egger_se = signif(egger_se, 2),
         Egger.pval = signif(Egger.pval, 2)) %>%
  tidyr::pivot_wider(names_from = method, names_glue = "{method}_{.value}", values_from = c(b, se, or, or_lci95, or_uci95, MR.pval)) %>%
  mutate(fdr = p.adjust(IVW_MR.pval, method = "fdr"),
         IVW_Signif = as.character(signif.num(IVW_MR.pval)),
         Egger_Signif = as.character(signif.num(Egger_MR.pval)),
         WME_Signif = as.character(signif.num(WME_MR.pval)),
         WMBE_Signif = as.character(signif.num(WMBE_MR.pval)),
         MRPRESSO_Raw_Signif = as.character(signif.num(MRPRESSO_Raw_MR.pval)),
         MRPRESSO_corrected_Signif = as.character(signif.num(MRPRESSO_corrected_MR.pval)))

## Spread by outlier removal MR-PRESSO
# mrresults.methods_presso <- mrresults.methods %>%
#   left_join(power) %>%
#   myspread(outliers_removed,
#            c(nsnp, n_outliers, pve.exposure, F, Power, RSSobs, MRPRESSO.pval,
#              egger_intercept, egger_se, Egger.pval,
#              snp_r2.exposure, snp_r2.outcome, correct_causal_direction, steiger_pval,
#              IVW_b, IVW_MR.pval, IVW_se,
#              Egger_b, Egger_MR.pval, Egger_se,
#              WME_b, WME_MR.pval, WME_se,
#              WMBE_b, WMBE_MR.pval, WMBE_se,
#              IVW_Signif, Egger_Signif, WME_Signif, WMBE_Signif)) %>%
#   arrange(pt, outcome, exposure) %>%
#   arrange(outcome.name, exposure.name, pt) %>%
#   select(outcome, exposure, outcome.name, exposure.name, pt, FALSE_nsnp, FALSE_pve.exposure, FALSE_F, FALSE_n_outliers,
#          FALSE_snp_r2.exposure, FALSE_snp_r2.outcome, FALSE_correct_causal_direction, FALSE_steiger_pval,
#          FALSE_IVW_b, FALSE_IVW_se, FALSE_IVW_MR.pval, FALSE_IVW_Signif, FALSE_Power,
#          FALSE_Egger_b, FALSE_Egger_se, FALSE_Egger_MR.pval, FALSE_Egger_Signif,
#          FALSE_WME_b, FALSE_WME_se, FALSE_WME_MR.pval, FALSE_WME_Signif,
#          FALSE_WMBE_b, FALSE_WMBE_se, FALSE_WMBE_MR.pval, FALSE_WMBE_Signif,
#          FALSE_RSSobs, FALSE_MRPRESSO.pval, FALSE_egger_intercept, FALSE_egger_se, FALSE_Egger.pval,
#          TRUE_snp_r2.exposure, TRUE_snp_r2.outcome, TRUE_correct_causal_direction, TRUE_steiger_pval,
#          TRUE_IVW_b, TRUE_IVW_se, TRUE_IVW_MR.pval, TRUE_IVW_Signif, TRUE_Power,
#          TRUE_Egger_b, TRUE_Egger_se, TRUE_Egger_MR.pval, TRUE_Egger_Signif,
#          TRUE_WME_b, TRUE_WME_se, TRUE_WME_MR.pval, TRUE_WME_Signif,
#          TRUE_WMBE_b, TRUE_WMBE_se, TRUE_WMBE_MR.pval, TRUE_WMBE_Signif,
#          TRUE_RSSobs, TRUE_MRPRESSO.pval, TRUE_egger_intercept, TRUE_egger_se, TRUE_Egger.pval) %>%
#   magrittr::set_colnames(colnames(.) %>% str_replace(., "FALSE_", "") %>% str_replace(., "TRUE_", "outlier_"))
```

```{r, write-wide-MR-results}
WideMRResults <- mrresults.methods %>%
  select(-outcome, -exposure, -exposure.domain, -outcome.domain, -ends_with("Signif")) %>%
  relocate(exposure.name, outcome.name)

```

```{r, eval=TRUE}
write_csv(WideMRResults, glue("results/{model}/All/{DATE}/{model}_WideMRResults.csv"))
```


## Best results

```{r mrbest}
## -------------------------------------------------------------------------------- ##
##                      Filter results for MR-PRESSO and best PT                    ##

passfunc <- function(ivw.p, ivw.b, mre.p, mre.b, wme.p, wme.b, wmb.p, wmb.b, mrpresso.p, mrpresso.b){
  ifelse(AllEqual(c(
    ifelse(ivw.p < 0.05, sign(ivw.b), NA),
    ifelse(mre.p < 0.05, sign(mre.b), NA),
    ifelse(wme.p < 0.05, sign(wme.b), NA),
    ifelse(wmb.p < 0.05, sign(wmb.b), NA),
    ifelse(mrpresso.p < 0.05, sign(mrpresso.b), NA)
  )) == TRUE,
  TRUE, FALSE)
}


mr_best <- mrresults.methods %>%
  mutate(MRPRESSO.pval_rm = as.numeric(str_replace(MRPRESSO.pval, '<', ""))) %>%
  mutate(pass = case_when(fdr > 0.05 ~ FALSE,
                          MRPRESSO.pval_rm > 0.05 & Egger.pval > 0.05 ~ TRUE,
                          Egger_MR.pval < 0.05 | WME_MR.pval < 0.05 | WMBE_MR.pval < 0.05 | MRPRESSO_corrected_MR.pval < 0.05 ~ TRUE,
                          TRUE ~ FALSE))  %>%
  split(., 1:nrow(.)) %>%
  map_dfr(., function(x){
    x %>%
      mutate(pass = ifelse(pass == FALSE, FALSE, passfunc(IVW_MR.pval, IVW_b,
                                                          Egger_MR.pval, Egger_b,
                                                          WME_MR.pval, WME_b,
                                                          WMBE_MR.pval, WMBE_b,
                                                          MRPRESSO_corrected_MR.pval, MRPRESSO_corrected_b)),
             )
  })

```

```{r, write-MRbest, eval=TRUE}
write_csv(mr_best, glue("docs/{DATE}/{model}_MRbest.csv"))
```

```{r, mr-out}
out.final <- mr_best %>%
  mutate(IVW = paste0(IVW_or, ' (', IVW_or_lci95, ', ', IVW_or_uci95, ')')) %>%
  mutate(`MR-Egger` = paste0(Egger_or, ' (', Egger_or_lci95, ', ', Egger_or_uci95, ')')) %>%
  mutate(`Weighted median` = paste0(WME_or, ' (', WME_or_lci95, ', ', WME_or_uci95, ')')) %>%
  mutate(`Weighted mode` = paste0(WMBE_or, ' (', WMBE_or_lci95, ', ', WMBE_or_uci95, ')')) %>%
  mutate(MRPRESSO = paste0(MRPRESSO_corrected_or, ' (', MRPRESSO_corrected_or_lci95, ', ', MRPRESSO_corrected_or_uci95, ')')) %>%
  mutate(Egger_I = paste0(egger_intercept, ' (', egger_se, ')')) %>%
  select(outcome, exposure, outcome.name, exposure.name, pt, nsnp, n_outliers, F, Isq,
         IVW, IVW_MR.pval, fdr,
         `MR-Egger`, Egger_MR.pval,
         `Weighted median`, WME_MR.pval,
         `Weighted mode`, WMBE_MR.pval,
         MRPRESSO, MRPRESSO_corrected_MR.pval,
         Egger_I, Egger.pval,
         RSSobs, MRPRESSO.pval, pass) %>%
  arrange(outcome.name, fdr) %>%
  # filter(outcome != "covidhgi2020A2v5alleur") %>%
  # mutate(fdr = p.adjust(IVW_MR.pval, "fdr")) %>%
  mutate(Egger.pval = round_sci(Egger.pval),
         fdr = round_sci(fdr),
         Isq = round(Isq, 2))  %>%
  map_dfr(., str_replace, "NA \\(NA, NA\\)", "") %>%
  map_dfr(., replace_na, "")

out.final %>% 
  filter(as.numeric(fdr) < 0.05) %>%
  # filter(pass == TRUE) %>%
  split(.$outcome)

```

```{r, write-publication-results, echo=FALSE, eval=TRUE}
write_csv(out.final, glue("docs/{DATE}/{model}_PublicationRes.csv"))
```

## Combined Plots

```{r dat-plot}
## Dataframe for ploting
dat.plot <- exposures_outcomes %>%
  # filter(!str_detect(outcomes.name, "eurLeaveUKBB")) %>%
  left_join(mr_best) %>%
  left_join(select(rg, p1, p2, rg, se_rg, rg.p, rg.fdr, rg.lci, rg.uci), by = c("exposure" = "p1", "outcome"= "p2")) %>%
  mutate(fdr_signif = ifelse(fdr <= 0.05, "*", " "),
         mr.p_cat = case_when(
           IVW_MR.pval <= 0.05 ~ 1,
           IVW_MR.pval <= 0.1 ~ 0.75,
           IVW_MR.pval <= 0.5 ~ 0.5,
           TRUE ~ 0.25,
           ),
         rg.fdr_signif = ifelse(rg.fdr <= 0.05, "*", " "),
         rg.p_cat = case_when(
           rg.p <= 0.05 ~ 1,
           rg.p <= 0.1 ~ 0.75,
           rg.p <= 0.5 ~ 0.5,
           TRUE ~ 0.25,
           )) %>%
  mutate(z = IVW_b/IVW_se,
         z = DescTools::Winsorize(z, maxval = 6)) %>%
  mutate(out = ifelse(fdr < 0.05, paste0(round(IVW_b, 3), '\n', '(', round_sci(fdr), ')'), " ")) %>%
  select(outcome, exposure, exposure.name, outcome.name, domain.exposure, domain.outcome,
         z, IVW_b, IVW_se, IVW_MR.pval, rg.p_cat, fdr, fdr_signif, out, pass, rg, rg.p, mr.p_cat, rg.fdr, rg.fdr_signif) %>%
  arrange(domain.exposure, desc(domain.outcome), outcome.name, exposure.name) %>%
  mutate(outcome.name = fct_inorder(outcome.name)) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  group_by(domain.exposure, domain.outcome) %>%
  arrange(exposure.name, outcome.name) %>%
  mutate(outcome.name = fct_inorder(fct_drop(outcome.name))) %>%
  mutate(exposure.name = fct_inorder(fct_drop(exposure.name))) %>%
  mutate(outcome1 = as.integer(fct_inorder(fct_drop(outcome.name)))) %>%
  mutate(exposure1 = as.integer(fct_inorder(fct_drop(exposure.name)))) %>%
  ungroup() %>%
  # mutate(outcome.name = fct_recode(outcome.name,
  #                                  A2 = "COVID: A2, EUR",
  #                                  B2 = "COVID: B2, EUR",
  #                                  C2 = "COVID: C2, EUR"))
  mutate(outcome.name = fct_recode(outcome.name,
                                   "Critical illness" = a2_pheno,
                                   Hospitalisation = b2_pheno,
                                   "Reported infection" = c2_pheno))

dat.long <- dat.plot %>%
  pivot_longer(c(z, rg), names_to = 'method', values_to = 'estimate') %>%
  mutate(mr = ifelse(method == 'z', estimate, NA),
         rg = ifelse(method == 'rg', estimate, NA),
         method = fct_recode(method, "Genetic \nCorrelation" = "rg", "Mendelian \nRandomization" = "z"), 
         domain.exposure = fct_relevel(domain.exposure, "Risk factor", "Biomarker", 'Disease liability'))

mrdat.p <- MRsummary %>%
  generate_odds_ratios(.) %>%
  filter(outliers_removed == FALSE) %>%
  filter(method != "MRPRESSO_Raw") %>%
  group_by(method) %>%
  mutate(fdr = p.adjust(MR.pval, "fdr")) %>%
  ungroup() %>%
  mutate(method = fct_relevel(method, "MRPRESSO_corrected", "Egger",  "WMBE",  "WME", "IVW"),
         method = fct_recode(method, "MR-PRESSO" = "MRPRESSO_corrected",  "MR Egger" =  "Egger")) %>%
  arrange(method, b) %>%
  mutate(exposure.name = fct_inorder(exposure.name),
         outcome.name = fct_recode(outcome.name,
                                   "Critical illness" = a2_pheno,
                                   Hospitalisation = b2_pheno,
                                   "Reported infection" = c2_pheno)
  )

mrdat.p.ls <- mrdat.p %>%
  semi_join(filter(mrdat.p, method == "IVW" & fdr < 0.05), by = c("exposure", "outcome")) %>%
  mutate(exposure.name = fct_recode(exposure.name,
                                    # "Education" = "Educational attainment",
                                    "RBC" = "Red blood cell count",
                                    "ALS" = "Amyotrophic lateral sclerosis",
                                    # "Age first birth" = "Age at first birth",
                                    "Parkinson's" = "Parkinsons disease",
                                    "Smoking" = "Smoking initiation", 
                                    "Mult. sclerosis" = "Multiple sclerosis")) %>%
  split(., .$outcome)

ggblank <- ggplot() + theme_void()

```

```{r}
# Plotting variables

## Colour Palatte
the_palette = "RdBu"

## Colour range
fun_color_range <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, the_palette)))
my_colors <- fun_color_range(1001)
df = tibble(x = -500:500, y = rep(1,1001), z = my_colors)

## Limites
rg_lim = c(-1, 1)
mr_lim = c(max(abs(dat.plot$z))*-1, max(abs(dat.plot$z)))

# https://eliocamp.github.io/codigo-r/2018/09/multiple-color-and-fill-scales-with-ggplot2/
# https://github.com/eliocamp/ggnewscale
library(ggnewscale)
# new_scale <- function(new_aes) {
#    structure(ggplot2::standardise_aes_names(new_aes), class = "new_aes")
# }
#
# ggplot_add.new_aes <- function(object, plot, object_name) {
#    plot$layers <- lapply(plot$layers, bump_aes, new_aes = object)
#    plot$scales$scales <- lapply(plot$scales$scales, bump_aes, new_aes = object)
#    plot$labels <- bump_aes(plot$labels, new_aes = object)
#    plot
# }

```


```{r}
# Heatmap of rg and MR results
## Facet by rg and MR, use new_scale to display to seperate scales
## geom_tile to use size of tile to represent significance
p3 <- ggplot(dat.long) +
  facet_grid(method ~ domain.exposure, scales = "free", space = "free", switch = "y") +
  # geom_raster(data = filter(dat.long, !is.na(rg)), aes(x = exposure.name, y = outcome.name, fill = rg)) +
  geom_tile(data = filter(dat.long, !is.na(rg)),
            aes(x = exposure.name, y = outcome.name, fill = rg, height=rg.p_cat, width=rg.p_cat)) +
  geom_text(data = filter(dat.long, !is.na(rg)),
            aes(label = rg.fdr_signif, x = exposure.name, y = outcome.name), vjust = 0.75, size = 4) +
  scale_fill_distiller(palette = rev(the_palette), limits = c(-1,1)) +
  new_scale("fill") +
  # geom_raster(data = filter(dat.long, !is.na(mr)), aes(x = exposure.name, y = outcome.name, fill = mr)) +
  geom_tile(data = filter(dat.long, !is.na(mr)),
            aes(x = exposure.name, y = outcome.name, fill = mr, height=mr.p_cat, width=mr.p_cat)) +
  scale_fill_distiller(palette = rev(the_palette), limits = c(-6,6)) +
  geom_text(data = filter(dat.long, !is.na(mr)),
            aes(label = fdr_signif, x = exposure.name, y = outcome.name), vjust = 0.75, size = 4) +
  theme_classic() +
  geom_vline(xintercept=seq(0.5, 43.5, 1),color="grey90") +
  geom_hline(yintercept=seq(0.5, 11.5, 1),color="grey90") +
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 35, hjust = 0),
        aspect.ratio=1,
        legend.text = element_text(hjust = 1.5),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.margin=margin(10,40,10,10, 'pt'),
        text = element_text(size=8),
        strip.text.y = element_text(size = 6),
        strip.background = element_blank(),
        # panel.border = element_rect(colour = "black", fill = NA)
        # legend.key.height = unit(0.75, "line"),
        # legend.spacing.y = unit(-0.75, "line"),
        # plot.margin=grid::unit(c(0,0,0,0), "mm")
  ) +
  scale_x_discrete(position = "top") +
  ylim(rev(levels(dat.long$outcome.name)))
# p3

## Use geom_point to hack togeather a legend
p.leg <- ggplot(df, aes(x = x, y = y, color = as.factor(x))) +
  geom_point(size = 1, shape = 15) +
  scale_color_manual(values = my_colors) +
  theme_void() +
  theme(legend.position = 'none') +
  annotate("segment", x = -50, y = 0.95, xend = -500, yend = 0.95, arrow=arrow(length=unit(2.5,"pt"), type = "closed")) +
  annotate("segment", x = 50, y = 0.95, xend = 500, yend = 0.95, arrow=arrow(length=unit(2.5,"pt"), type = "closed")) +
  annotate("text", x = -450, y = 0.91, label = "Negative/Protective", size = 2) +
  annotate("text", x = 465, y = 0.91, label = "Positive/Risk", size = 2) +
  annotate("text", x = 0, y = 0.91, label = "rg/MR", size = 2) +
  theme(legend.position = 'none',
        # aspect.ratio=1/10,
        text = element_text(size=8),
        plot.margin=margin(0,0,0,0, 'pt'),
        ) +
    expand_limits(y = c(0.8, 1.1))

## Put some padding around the legend
p.leg_out <- ggarrange(ggblank, p.leg, ggblank,
                       nrow = 1, ncol = 3, widths = c(0.1, 1, 0.026))

## combine heatmap and legend
p.heatmap <- ggarrange(p3, p.leg_out, nrow = 2, ncol = 1, heights = c(1,0.15))
# p.heatmap
```


```{r}

mrforrest_plot <- function(x){
  mr_lim <- max(
    max(abs(x$lo_ci), na.rm = T),
    max(abs(x$up_ci), na.rm = T)
    ) %>% round(., 1)

  mr_labels = x %>%
    select(outcome, exposure, exposure.name, method, Egger.pval, MRPRESSO.pval, b, lo_ci, up_ci, or) %>%
    mutate(Egger.pval = signif(Egger.pval, 2),
           Egger.out = glue("Egger Intercept, p = {Egger.pval}"),
           MRPRESSO.out = glue("MR-PRESSO GT, p = {MRPRESSO.pval}"),
           # out = glue("{Egger.out}, \n{MRPRESSO.out}"),
           or = ifelse(b > 0, mr_lim*-1, mr_lim)
           ) %>%
    filter(method %in% c("IVW", "WME")) %>%
    pivot_longer(c("Egger.out", "MRPRESSO.out"), names_to = "out") %>%
    arrange(method, out) %>%
    filter(method == "IVW" & out == "Egger.out" | method == "WME" & out == "MRPRESSO.out")

  ggplot(x,
         # aes(y = method, x = or)
         aes(y = method, x = b)
  ) +
    # geom_vline(xintercept = 1, linetype = 2) +
    geom_vline(xintercept = 0, linetype = 2) +
    facet_grid(exposure.name ~ outcome.name, scales = "free_x", space = "free") +
    geom_point() +
    # geom_linerange(aes(xmin = or_lci95, xmax = or_uci95)) +
    geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
    theme_bw() +
    labs(title = " ", x = "logOR (95%CI)") +
    theme(legend.position = "none",
          axis.title.y=element_blank(),
          axis.title.x=element_text(size=8),
          panel.grid.minor.x  = element_blank(),
          text = element_text(size=8),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA)) +
    expand_limits(y = 6) +
    geom_label(
      data    = mr_labels,
      mapping = aes(x = or, y = method, label = value, alpha = 0),
      nudge_x = 0,
      nudge_y = 0.5,
      size = 1.5,
      hjust = "inward",
      label.size = NA
    )
}

p.ls <- map(mrdat.p.ls, mrforrest_plot)

p4 <- ggarrange(p.ls[[1]], ggblank, nrow = 2, ncol = 1, heights = c(1, 1.65))
p5 <- ggarrange(p.ls[[2]], ggblank, nrow = 2, ncol = 1, heights = c(3.75, 1))

p.mr_sig <- ggarrange(ggblank, p4, p5, p.ls[[3]], ggblank,
                      nrow = 1, ncol = 5, widths = c(0.19, 1, 1, 1, 0.09))


```


```{r}
p.comb <- ggarrange(p.heatmap, p.mr_sig, nrow = 2, ncol = 1,  heights = c(1, 1.5))
# p.comb

# ggsave(glue("docs/{DATE}/{model}_MR_RG_heatmap{DATE}.png"), plot = p3, width = 11, height = 5, units = "in")
ggsave(glue("docs/{DATE}/{model}_resplot.png"), plot = p.comb, height = 190, width = 240, units = 'mm')
ggsave(glue("docs/{DATE}/{model}_resplot.tiff"), plot = p.comb, height = 190, width = 240, units = 'mm')
ggsave(glue("docs/{DATE}/{model}_resplot.pdf"), plot = p.comb, height = 190, width = 240, units = 'mm')
```

## Heatmap

```{r heatmap,  fig.fullwidth=TRUE}
# rg
p1 <- ggplot(dat.plot) +
  facet_grid(. ~ domain.exposure, scales = "free", space = "free", switch = "y") +
  geom_tile(aes(x = exposure.name, y = outcome.name, fill = rg, height=rg.p_cat, width=rg.p_cat)) +
  geom_text(data = dat.plot, vjust = 0.75, size = 4, aes(label = rg.fdr_signif, x = exposure.name, y = outcome.name)) +
  scale_fill_distiller(palette = rev(the_palette), limits = rg_lim) +
  theme_classic() +
  scale_x_discrete(position = "top") +
  geom_vline(xintercept=seq(0.5, 43.5, 1),color="grey90") +
  geom_hline(yintercept=seq(0.5, 11.5, 1),color="grey90") +
  theme(legend.position = 'right',
        legend.title=element_blank(),
        legend.text = element_text(hjust = 1.5), text = element_text(size=10),
        axis.text.x = element_text(angle = 35, hjust = 0),
        # axis.text.x = element_blank(),
        # axis.ticks.x = element_blank(),
        # strip.text.x = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(),
        aspect.ratio=1,
        legend.key.width = unit(0.5, "line"),
        legend.key.height = unit(0.75, "line"),
        legend.spacing.y = unit(-0.75, "line"),
        # plot.margin=grid::unit(c(0,0,0,0), "mm"),
         strip.background = element_blank()
        )
p1

# MR
p2 <- ggplot(dat.plot) +
  facet_grid(. ~ domain.exposure, scales = "free", space = "free", switch = "y") +
  geom_tile(aes(x = exposure.name, y = outcome.name, fill = z, height=mr.p_cat, width=mr.p_cat)) +
  geom_text(data = dat.plot, vjust = 0.75, size = 4, aes(label = fdr_signif, x = exposure.name, y = outcome.name)) +
  scale_fill_distiller(palette = rev(the_palette), limits = mr_lim) +
  theme_classic() +
  scale_x_discrete(position = "top") +
  geom_vline(xintercept=seq(0.5, 43.5, 1),color="grey90") +
  geom_hline(yintercept=seq(0.5, 11.5, 1),color="grey90") +
  geom_rect(data = filter(dat.plot, pass == TRUE), size=0.5, fill=NA, colour="black",
            aes(xmin=exposure1 - 0.5, xmax=exposure1 + 0.5,
                ymin=outcome1 - 0.5, ymax=outcome1 + 0.5)) +
  theme(legend.position = 'right',
        legend.title=element_blank(),
        legend.text = element_text(hjust = 1.5), text = element_text(size=10),
        axis.text.x = element_text(angle = 35, hjust = 0),
        # axis.text.x = element_blank(),
        # axis.ticks.x = element_blank(),
        # strip.text.x = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(),
        aspect.ratio=1,
        legend.key.width = unit(0.5, "line"),
        legend.key.height = unit(0.75, "line"),
        legend.spacing.y = unit(-0.75, "line"),
        # plot.margin=grid::unit(c(0,0,0,0), "mm"),
         strip.background = element_blank()
        )
p2

```

```{r}
## Put some padding around the legend
p.leg_out2 <- ggarrange(ggblank, p.leg, ggblank,
                       nrow = 1, ncol = 3, widths = c(0.075, 1, 0.012))

## combine heatmap and legend
p.heatmap2 <- ggarrange(p3, p.leg_out2, nrow = 2, ncol = 1, heights = c(1,0.15))
ggsave(glue("docs/{DATE}/{model}_MR_RGheatmap.png"), plot = p.heatmap2, width = 11, height = 3.5, units = "in")

ggsave(glue("docs/{DATE}/{model}_MRheatmap.png"), plot = p2, width = 11, height = 5, units = "in")
ggsave(glue("docs/{DATE}/{model}_RGheatmap.png"), plot = p1, width = 11, height = 5, units = "in")
```

## RG forrest plots 
```{r}
rg_covid_comp <- bind_rows(
  rg_covid, 
  rg_covid %>% rename(p2 = p1, p1 = p2, outcome.name = exposure.name, exposure.name = outcome.name)
)

forrest_dat.p <- rg %>%
    bind_rows(rg_covid_comp) %>%
    mutate(method = 'rg') %>%
    rename(exposure = p1, outcome = p2, b = rg, p = rg.p, lo_ci = rg.lci, up_ci = rg.uci, fdr = rg.fdr) %>%
    select(outcome, exposure, exposure.name, outcome.name, method, b, lo_ci, up_ci, p, fdr) %>%
    mutate(signif = case_when(p > 0.05 ~ "NS",
                            p < 0.05 & fdr > 0.05 ~ "Nominal",
                            p <= 0.05 ~ "Significant"),
         signif = fct_relevel(signif, "NS", "Nominal", "Significant"),
         method = fct_rev(method)
  ) %>%
  split(.$outcome) %>%
  map(., arrange, method, b) %>%
  map(., mutate, exposure.name = fct_inorder(exposure.name)) %>% 
  bind_rows() %>%
  mutate(outcome.name = fct_recode(outcome.name,
                                   "Critical illness" = a2_pheno,
                                   Hospitalisation = b2_pheno,
                                   "Reported infection" = c2_pheno)) %>% 
  mutate(covid_panel = ifelse(exposure.name %in% c("Critical illness", "Hospitalisation", "Reported infection"), 1, 2))


rg_forrest_plot <- ggplot(forrest_dat.p, aes(y = exposure.name, x = b, colour = signif)) +
    geom_vline(xintercept = 0, linetype = 2) +
    geom_point() +
    geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
    scale_color_manual(values = c("grey75", "black", "red")) +
    theme_bw() +
    facet_grid(covid_panel ~ outcome.name, scales = "free", space = "free_y") +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          axis.title=element_blank(),
          strip.background = element_blank(),
          strip.text.y = element_blank(),
          strip.placement = "outside",
          panel.grid.minor.x  = element_blank())

ggsave(glue("docs/{DATE}/{model}_rg_forrest_plot.png"), plot = rg_forrest_plot, height = 190, width = 240, units = 'mm')

```

## Forrest plots
### Including UKB

```{r}
## Format datasets
forrest_dat.p <- bind_rows(
  rg %>%
    mutate(method = 'rg') %>%
    rename(exposure = p1, outcome = p2, b = rg, p = rg.p, lo_ci = rg.lci, up_ci = rg.uci, fdr = rg.fdr) %>%
    select(outcome, exposure, exposure.name, outcome.name, method, b, lo_ci, up_ci, p, fdr),

  MRsummary %>%
    filter(method == "IVW") %>%
    generate_odds_ratios(.) %>%
    filter(outliers_removed == FALSE) %>%
    mutate(fdr = p.adjust(MR.pval, "fdr")) %>%
    select(outcome, exposure, exposure.name, outcome.name, method, b, lo_ci, up_ci, p = MR.pval, fdr)
) %>%
  mutate(signif = case_when(p > 0.05 ~ "NS",
                            p < 0.05 & fdr > 0.05 ~ "Nominal",
                            p <= 0.05 ~ "Significant"),
         signif = fct_relevel(signif, "NS", "Nominal", "Significant"),
         method = fct_rev(method)
  ) %>%
  left_join(rg %>%
              mutate(rg_panel = ifelse(rg.fdr < 0.05, "TRUE", "FALSE"),
                     rg_panel = replace_na(rg_panel, "FALSE"),
                     rg_panel = fct_relevel(rg_panel, "TRUE", "FALSE")) %>%
              select(outcome = p2, exposure = p1, exposure.name, outcome.name, rg_panel)
            ) %>%
  split(.$outcome) %>%
  map(., arrange, method, b) %>%
  map(., mutate, exposure.name = fct_inorder(exposure.name))

```


```{r}
## Plot forrest plot
forrest.p <- map(forrest_dat.p, function(x){
  ggplot(x, aes(y = exposure.name, x = b, colour = signif)) +
  geom_vline(xintercept = 0, linetype = 2) +
  facet_grid(rg_panel ~ method, scales = "free", space = "free_y",
             switch="both",
             labeller = as_labeller(
               c(IVW = "Mendelian Randomization \nlogOR (95%CI)",
                 rg = "Genetic Correlation \nrg (95%CI)")
               )
             ) +
  geom_point() +
  geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
  scale_color_manual(values = c("grey75", "black", "red")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.title=element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        strip.placement = "outside",
        panel.grid.minor.x  = element_blank())
})

## Arrange and align MR sensetivity plots
forrest_out.p <- map2(forrest.p, p.ls, function(x, y){
  p1 = x
  p2 = y + theme(strip.text.x = element_blank())
  cowplot::plot_grid(plotlist = list(p1,p2), nrow = 1, ncol = 2,  align = 'h',  axis = "bt", rel_widths = c(1.5, 1))
  }
)
```


```{r}
ggsave(glue("docs/{DATE}/{model}_covidhgi2020A2v5alleur_forrest.png"),
       plot = forrest_out.p[[1]], width = 12, height = 6, units = "in")

ggsave(glue("docs/{DATE}/{model}_covidhgi2020B2v5alleur_forrest.png"),
       plot = forrest_out.p[[2]], width = 12, height = 6, units = "in")

ggsave(glue("docs/{DATE}/{model}_covidhgi2020C2v5alleur_forrest.png"),
       plot = forrest_out.p[[3]], width = 12, height = 6, units = "in")

```


### Excluding UKB
#### COVID-A2
```{r}
mrdatA2.p <- MRsummary %>%
  generate_odds_ratios(.) %>%
  filter(outliers_removed == FALSE) %>%
  group_by(method) %>%
  mutate(fdr = p.adjust(MR.pval, "fdr")) %>%
  ungroup() %>%
  left_join(select(rg, p1, p2, rg, se_rg, rg.p, rg.fdr, rg.lci, rg.uci), by = c("exposure" = "p1", "outcome"= "p2")) %>%
  filter(outcome == "covidhgi2020A2v5alleurLeaveUKBB") %>%
  filter(method != "MRPRESSO_Raw") %>%
  mutate(method = fct_relevel(method, "MRPRESSO_corrected", "Egger",  "WMBE",  "WME", "IVW"),
         method = fct_recode(method, "MR-PRESSO" = "MRPRESSO_corrected",  "MR Egger" =  "Egger")) %>%
  arrange(method, b) %>%
  mutate(exposure.name = fct_inorder(exposure.name),
         rg_panel = ifelse(rg.fdr < 0.05, "TRUE", "FALSE"),
         rg_panel = replace_na(rg_panel, "FALSE"),
         rg_panel = fct_relevel(rg_panel, "TRUE", "FALSE"),
         rg_signif = case_when(rg.p > 0.05 ~ "NS",
                               rg.p < 0.05 & rg.fdr > 0.05 ~ "Nominal",
                               rg.fdr < 0.05 ~ "Significant"),
         rg_signif = replace_na(rg_signif, "NS"),
         rg_signif = fct_relevel(rg_signif, "NS", "Nominal", "Significant"),
         mr_signif = case_when(MR.pval > 0.05 ~ "NS",
                               MR.pval < 0.05 & fdr > 0.05 ~ "Nominal",
                               fdr < 0.05 ~ "Significant"),
         mr_signif = fct_relevel(mr_signif, "NS", "Nominal", "Significant"),
         up_ci_arrow = ifelse(up_ci > 5, 5, NA),
         lo_ci_arrow = ifelse(lo_ci < -5, -5, NA),
         lo_ci = ifelse(lo_ci < -5, -5, lo_ci),
         up_ci = ifelse(up_ci > 5, 5, up_ci),
         )

rgA2.p <- mrdatA2.p %>%
  arrange(method, rg) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  ggplot(., aes(y = exposure.name, x = rg, colour = rg_signif)) +
    geom_vline(xintercept = 0, linetype = 2) +
    facet_grid(rg_panel ~ ., scales = "free_y", space = "free") +
    geom_point() +
    geom_linerange(aes(xmin = rg.lci, xmax = rg.uci)) +
    scale_color_manual(values = c("grey75", "black", "red")) +
    theme_bw() +
    labs(title = "Genetic correlation", x = "rg (95%CI)") +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          axis.title.y=element_blank(),
          strip.background = element_blank(),
          strip.text.y = element_blank(),
          panel.grid.minor.x  = element_blank())

mrA2.p <- mrdatA2.p %>%
  filter(method == "IVW") %>%
  arrange(method, rg) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  ggplot(.,
         # aes(y = exposure.name, x = or, colour = mr_signif)
         aes(y = exposure.name, x = b, colour = mr_signif)
         ) +
    # geom_vline(xintercept = 1, linetype = 2) +
    geom_vline(xintercept = 0, linetype = 2) +
    facet_grid(rg_panel ~ ., scales = "free_y", space = "free") +
    geom_point() +
    # geom_linerange(aes(xmin = or_lci95, xmax = or_uci95)) +
    geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
    scale_color_manual(values = c("grey75", "black", "red")) +
    # scale_x_continuous(trans='log2') +
    # scale_x_continuous(trans=pseudolog10_trans, breaks = c(-4, -2, -1, 1, 2)) +
    expand_limits(x = 2.5) +
    theme_bw() +
    labs(title = "Mendelian randomization (IVW)", x = "logOR (95%CI)") +
    # labs(title = "Mendealian randomization", x = "OR (95%CI)") +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          strip.background = element_blank(),
          strip.text.y = element_blank(),
          panel.grid.minor.x  = element_blank())

ann_textA2 <- mrdatA2.p %>%
  filter(exposure %in% c("Yengo2018bmi", "Lee2018educ")) %>%
  filter(method %in% c("IVW", "WME")) %>%
  select(outcome, exposure, exposure.name, method, Egger.pval, MRPRESSO.pval, or) %>%
  mutate(exposure.name = fct_recode(exposure.name,
                                    "Education" = "Educational Attainment",
                                    # "AFB" = "Age at first birth",
                                    "Smoking" = "Smoking Initiation"),
         Egger.pval = signif(Egger.pval, 2),
         Egger.out = glue("Egger Intercept, p = {Egger.pval}"),
         MRPRESSO.out = glue("MR-PRESSO GT, p = {MRPRESSO.pval}"),
         # out = glue("{Egger.out}, \n{MRPRESSO.out}"),
         or = 2.5
         ) %>%
  pivot_longer(c("Egger.out", "MRPRESSO.out"), names_to = "out") %>%
  arrange(method, out) %>%
  filter(method == "IVW" & out == "Egger.out" | method == "WME" & out == "MRPRESSO.out")


mrA2.sig <- mrdatA2.p %>%
  filter(exposure %in% c("Yengo2018bmi", "Lee2018educ")) %>%
    mutate(exposure.name = fct_recode(exposure.name,
                                    "Education" = "Educational Attainment",
                                    # "AFB" = "Age at first birth",
                                    "Smoking" = "Smoking Initiation")) %>%
  ggplot(.,
         # aes(y = method, x = or)
         aes(y = method, x = b)
  ) +
  # geom_vline(xintercept = 1, linetype = 2) +
  geom_vline(xintercept = 0, linetype = 2) +
  facet_grid(exposure.name ~ ., scales = "free_x", space = "free") +
  geom_point() +
  # geom_linerange(aes(xmin = or_lci95, xmax = or_uci95)) +
  geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
  geom_segment(aes(xend = up_ci_arrow, yend = method), arrow = arrow(length = unit(0.2,"cm"))) +
  geom_segment(aes(xend = lo_ci_arrow, yend = method), arrow = arrow(length = unit(0.2,"cm"))) +
  scale_color_manual(values = c("grey50", "black", "red")) +
  # scale_x_continuous(trans='log2') +
  # scale_x_continuous(trans=pseudolog10_trans, breaks = c(-10, -5, -1, 1, 5, 10)) +
  geom_label(
    data    = ann_textA2,
    mapping = aes(x = or, y = method, label = value),
    nudge_x = 0,
    nudge_y = 0.5,
    size = 2,
    hjust = "inward",
    label.size = NA
  ) +
  theme_bw() +
  # labs(title = " ", x = "OR (95%CI)") +
  labs(title = " ", x = "logOR (95%CI)") +
  theme(legend.position = "none",
        axis.title.y=element_blank(),
        panel.grid.minor.x  = element_blank()) +
  expand_limits(y = 6) +
  coord_cartesian(xlim = c(-2.5, 2.5))


ggarrange(rgA2.p, mrA2.p, mrA2.sig, nrow = 1, ncol = 3, widths = c(1.25, 1), common.legend = TRUE, legend = "bottom")  %>%
  annotate_figure(., top = text_grob("COVID-A2, EUR w/o UKB", face = "bold", size = 14))
ggsave(glue("docs/{DATE}/{model}_covidhgi2020A2v5alleurLeaveUKBB_forrest.png"), width = 12, height = 6, units = "in")
```


#### COVID-B2
```{r}
mrdatB2.p <- MRsummary %>%
  generate_odds_ratios(.) %>%
  filter(outliers_removed == FALSE) %>%
  group_by(method) %>%
  mutate(fdr = p.adjust(MR.pval, "fdr")) %>%
  ungroup() %>%
  left_join(select(rg, p1, p2, rg, se_rg, rg.p, rg.fdr, rg.lci, rg.uci), by = c("exposure" = "p1", "outcome"= "p2")) %>%
  filter(outcome == "covidhgi2020B2v5alleurLeaveUKBB") %>%
  filter(method != "MRPRESSO_Raw") %>%
  mutate(method = fct_relevel(method, "MRPRESSO_corrected", "Egger",  "WMBE",  "WME", "IVW"),
         method = fct_recode(method, "MR-PRESSO" = "MRPRESSO_corrected",  "MR Egger" =  "Egger")) %>%
  arrange(method, b) %>%
  mutate(exposure.name = fct_inorder(exposure.name),
         rg_panel = ifelse(rg.fdr < 0.05, "TRUE", "FALSE"),
         rg_panel = replace_na(rg_panel, "FALSE"),
         rg_panel = fct_relevel(rg_panel, "TRUE", "FALSE"),
         rg_signif = case_when(rg.p > 0.05 ~ "NS",
                               rg.p < 0.05 & rg.fdr > 0.05 ~ "Nominal",
                               rg.fdr < 0.05 ~ "Significant"),
         rg_signif = replace_na(rg_signif, "NS"),
         rg_signif = fct_relevel(rg_signif, "NS", "Nominal", "Significant"),
         mr_signif = case_when(MR.pval > 0.05 ~ "NS",
                               MR.pval < 0.05 & fdr > 0.05 ~ "Nominal",
                               fdr < 0.05 ~ "Significant"),
         mr_signif = fct_relevel(mr_signif, "NS", "Nominal", "Significant"),
         up_ci_arrow = ifelse(up_ci > 5, 5, NA),
         lo_ci_arrow = ifelse(lo_ci < -5, -5, NA),
         lo_ci = ifelse(lo_ci < -5, -5, lo_ci),
         up_ci = ifelse(up_ci > 5, 5, up_ci),
         )

rgB2.p <- mrdatB2.p %>%
  arrange(method, rg) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  ggplot(., aes(y = exposure.name, x = rg, colour = rg_signif)) +
    geom_vline(xintercept = 0, linetype = 2) +
    facet_grid(rg_panel ~ ., scales = "free_y", space = "free") +
    geom_point() +
    geom_linerange(aes(xmin = rg.lci, xmax = rg.uci)) +
    scale_color_manual(values = c("grey75", "black", "red")) +
    theme_bw() +
    labs(title = "Genetic correlation", x = "rg (95%CI)") +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          axis.title.y=element_blank(),
          strip.background = element_blank(),
          strip.text.y = element_blank(),
          panel.grid.minor.x  = element_blank())

mrB2.p <- mrdatB2.p %>%
  filter(method == "IVW") %>%
  arrange(method, rg) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  ggplot(.,
         # aes(y = exposure.name, x = or, colour = mr_signif)
         aes(y = exposure.name, x = b, colour = mr_signif)
         ) +
    # geom_vline(xintercept = 1, linetype = 2) +
    geom_vline(xintercept = 0, linetype = 2) +
    facet_grid(rg_panel ~ ., scales = "free_y", space = "free") +
    geom_point() +
    # geom_linerange(aes(xmin = or_lci95, xmax = or_uci95)) +
    geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
    scale_color_manual(values = c("grey75", "black", "red")) +
    # scale_x_continuous(trans='log2') +
    # scale_x_continuous(trans=pseudolog10_trans, breaks = c(-4, -2, -1, 1, 2)) +
    expand_limits(x = 2.5) +
    theme_bw() +
    labs(title = "Mendelian randomization (IVW)", x = "logOR (95%CI)") +
    # labs(title = "Mendealian randomization", x = "OR (95%CI)") +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          strip.background = element_blank(),
          strip.text.y = element_blank(),
          panel.grid.minor.x  = element_blank())

ann_textB2 <- mrdatB2.p %>%
  filter(exposure %in% c("Yengo2018bmi", "Lee2018educ", "Liu2019smkint", "Mills2021afb", "Nalls2019pd")) %>%
  filter(method %in% c("IVW", "WME")) %>%
  select(outcome, exposure, exposure.name, method, Egger.pval, MRPRESSO.pval, or) %>%
  mutate(exposure.name = fct_recode(exposure.name,
                                    "Education" = "Educational Attainment",
                                    # "AFB" = "Age at first birth",
                                    "Smoking" = "Smoking Initiation"),
         Egger.pval = signif(Egger.pval, 2),
         Egger.out = glue("Egger Intercept, p = {Egger.pval}"),
         MRPRESSO.out = glue("MR-PRESSO GT, p = {MRPRESSO.pval}"),
         # out = glue("{Egger.out}, \n{MRPRESSO.out}"),
         or = 2.5
         ) %>%
  pivot_longer(c("Egger.out", "MRPRESSO.out"), names_to = "out") %>%
  arrange(method, out) %>%
  filter(method == "IVW" & out == "Egger.out" | method == "WME" & out == "MRPRESSO.out")


mrB2.sig <- mrdatB2.p %>%
  filter(exposure %in% c("Yengo2018bmi", "Lee2018educ", "Liu2019smkint", "Mills2021afb", "Nalls2019pd")) %>%
    mutate(exposure.name = fct_recode(exposure.name,
                                    "Education" = "Educational Attainment",
                                    # "AFB" = "Age at first birth",
                                    "Smoking" = "Smoking Initiation")) %>%
  ggplot(.,
         # aes(y = method, x = or)
         aes(y = method, x = b)
  ) +
  # geom_vline(xintercept = 1, linetype = 2) +
  geom_vline(xintercept = 0, linetype = 2) +
  facet_grid(exposure.name ~ ., scales = "free_x", space = "free") +
  geom_point() +
  # geom_linerange(aes(xmin = or_lci95, xmax = or_uci95)) +
  geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
  geom_segment(aes(xend = up_ci_arrow, yend = method), arrow = arrow(length = unit(0.2,"cm"))) +
  geom_segment(aes(xend = lo_ci_arrow, yend = method), arrow = arrow(length = unit(0.2,"cm"))) +
  scale_color_manual(values = c("grey50", "black", "red")) +
  # scale_x_continuous(trans='log2') +
  # scale_x_continuous(trans=pseudolog10_trans, breaks = c(-10, -5, -1, 1, 5, 10)) +
  geom_label(
    data    = ann_textB2,
    mapping = aes(x = or, y = method, label = value),
    nudge_x = 0,
    nudge_y = 0.5,
    size = 2,
    hjust = "inward",
    label.size = NA
  ) +
  theme_bw() +
  # labs(title = " ", x = "OR (95%CI)") +
  labs(title = " ", x = "logOR (95%CI)") +
  theme(legend.position = "none",
        axis.title.y=element_blank(),
        panel.grid.minor.x  = element_blank()) +
  expand_limits(y = 6) +
  coord_cartesian(xlim = c(-3, 3))


ggarrange(rgB2.p, mrB2.p, mrB2.sig, nrow = 1, ncol = 3, widths = c(1.25, 1), common.legend = TRUE, legend = "bottom") %>%
  annotate_figure(., top = text_grob("COVID-B2, EUR w/o UKB", face = "bold", size = 14))
ggsave(glue("docs/{DATE}/{model}_covidhgi2020B2v5alleurLeaveUKBB_forrest.png"), width = 12, height = 6, units = "in")
```

#### COVID-C2
```{r}
mrdatC2.p <- MRsummary %>%
  generate_odds_ratios(.) %>%
  filter(outliers_removed == FALSE) %>%
  group_by(method) %>%
  mutate(fdr = p.adjust(MR.pval, "fdr")) %>%
  ungroup() %>%
  left_join(select(rg, p1, p2, rg, se_rg, rg.p, rg.fdr, rg.lci, rg.uci), by = c("exposure" = "p1", "outcome"= "p2")) %>%
  filter(outcome == "covidhgi2020C2v5alleurLeaveUKBB") %>%
  filter(method != "MRPRESSO_Raw") %>%
  mutate(method = fct_relevel(method, "MRPRESSO_corrected", "Egger",  "WMBE",  "WME", "IVW"),
         method = fct_recode(method, "MR-PRESSO" = "MRPRESSO_corrected",  "MR Egger" =  "Egger")) %>%
  arrange(method, b) %>%
  mutate(exposure.name = fct_inorder(exposure.name),
         rg_panel = ifelse(rg.fdr < 0.05, "TRUE", "FALSE"),
         rg_panel = replace_na(rg_panel, "FALSE"),
         rg_panel = fct_relevel(rg_panel, "TRUE", "FALSE"),
         rg_signif = case_when(rg.p > 0.05 ~ "NS",
                               rg.p < 0.05 & rg.fdr > 0.05 ~ "Nominal",
                               rg.fdr < 0.05 ~ "Significant"),
         rg_signif = replace_na(rg_signif, "NS"),
         rg_signif = fct_relevel(rg_signif, "NS", "Nominal", "Significant"),
         mr_signif = case_when(MR.pval > 0.05 ~ "NS",
                               MR.pval < 0.05 & fdr > 0.05 ~ "Nominal",
                               fdr < 0.05 ~ "Significant"),
         mr_signif = fct_relevel(mr_signif, "NS", "Nominal", "Significant"),
         up_ci_arrow = ifelse(up_ci > 5, 5, NA),
         lo_ci_arrow = ifelse(lo_ci < -5, -5, NA),
         lo_ci = ifelse(lo_ci < -5, -5, lo_ci),
         up_ci = ifelse(up_ci > 5, 5, up_ci),
         )

rgC2.p <- mrdatC2.p %>%
  arrange(method, rg) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  ggplot(., aes(y = exposure.name, x = rg, colour = rg_signif)) +
    geom_vline(xintercept = 0, linetype = 2) +
    facet_grid(rg_panel ~ ., scales = "free_y", space = "free") +
    geom_point() +
    geom_linerange(aes(xmin = rg.lci, xmax = rg.uci)) +
    scale_color_manual(values = c("grey75", "black", "red")) +
    theme_bw() +
    labs(title = "Genetic correlation", x = "rg (95%CI)") +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          axis.title.y=element_blank(),
          strip.background = element_blank(),
          strip.text.y = element_blank(),
          panel.grid.minor.x  = element_blank())

mrC2.p <- mrdatC2.p %>%
  filter(method == "IVW") %>%
  arrange(method, rg) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  mutate(exposure.name = fct_inorder(exposure.name)) %>%
  ggplot(.,
         # aes(y = exposure.name, x = or, colour = mr_signif)
         aes(y = exposure.name, x = b, colour = mr_signif)
         ) +
    # geom_vline(xintercept = 1, linetype = 2) +
    geom_vline(xintercept = 0, linetype = 2) +
    facet_grid(rg_panel ~ ., scales = "free_y", space = "free") +
    geom_point() +
    # geom_linerange(aes(xmin = or_lci95, xmax = or_uci95)) +
    geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
    scale_color_manual(values = c("grey75", "black", "red")) +
    # scale_x_continuous(trans='log2') +
    # scale_x_continuous(trans=pseudolog10_trans, breaks = c(-4, -2, -1, 1, 2)) +
    expand_limits(x = 1.5) +
    theme_bw() +
    labs(title = "Mendelian randomization (IVW)", x = "logOR (95%CI)") +
    # labs(title = "Mendealian randomization", x = "OR (95%CI)") +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          strip.background = element_blank(),
          strip.text.y = element_blank(),
          panel.grid.minor.x  = element_blank())

ann_textC2 <- mrdatC2.p %>%
  filter(exposure %in% c("Yengo2018bmi", "Wood2014height", "Astel2016rbc", "Nicolas2018als")) %>%
  filter(method %in% c("IVW", "WME")) %>%
  select(outcome, exposure, exposure.name, method, Egger.pval, MRPRESSO.pval, or) %>%
  mutate(exposure.name = fct_recode(exposure.name,
                                    "Education" = "Educational Attainment",
                                    # "AFB" = "Age at first birth",
                                    "Smoking" = "Smoking Initiation"),
         Egger.pval = signif(Egger.pval, 2),
         Egger.out = glue("Egger Intercept, p = {Egger.pval}"),
         MRPRESSO.out = glue("MR-PRESSO GT, p = {MRPRESSO.pval}"),
         # out = glue("{Egger.out}, \n{MRPRESSO.out}"),
         or = 1
         ) %>%
  pivot_longer(c("Egger.out", "MRPRESSO.out"), names_to = "out") %>%
  arrange(method, out) %>%
  filter(method == "IVW" & out == "Egger.out" | method == "WME" & out == "MRPRESSO.out")


mrC2.sig <- mrdatC2.p %>%
  filter(exposure %in% c("Yengo2018bmi", "Wood2014height", "Astel2016rbc", "Nicolas2018als")) %>%
    mutate(exposure.name = fct_recode(exposure.name,
                                    "Education" = "Educational Attainment",
                                    # "AFB" = "Age at first birth",
                                    "Smoking" = "Smoking Initiation")) %>%
  ggplot(.,
         # aes(y = method, x = or)
         aes(y = method, x = b)
  ) +
  # geom_vline(xintercept = 1, linetype = 2) +
  geom_vline(xintercept = 0, linetype = 2) +
  facet_grid(exposure.name ~ ., scales = "free_x", space = "free") +
  geom_point() +
  # geom_linerange(aes(xmin = or_lci95, xmax = or_uci95)) +
  geom_linerange(aes(xmin = lo_ci, xmax = up_ci)) +
  # geom_segment(aes(xend = up_ci_arrow, yend = method), arrow = arrow(length = unit(0.2,"cm"))) +
  # geom_segment(aes(xend = lo_ci_arrow, yend = method), arrow = arrow(length = unit(0.2,"cm"))) +
  scale_color_manual(values = c("grey50", "black", "red")) +
  # scale_x_continuous(trans='log2') +
  # scale_x_continuous(trans=pseudolog10_trans, breaks = c(-10, -5, -1, 1, 5, 10)) +
  geom_label(
    data    = ann_textC2,
    mapping = aes(x = or, y = method, label = value),
    nudge_x = 0,
    nudge_y = 0.5,
    size = 2,
    hjust = "inward",
    label.size = NA
  ) +
  theme_bw() +
  # labs(title = " ", x = "OR (95%CI)") +
  labs(title = " ", x = "logOR (95%CI)") +
  theme(legend.position = "none",
        axis.title.y=element_blank(),
        panel.grid.minor.x  = element_blank()) +
  expand_limits(y = 6) +
  coord_cartesian(xlim = c(-1, 1))


ggarrange(rgC2.p, mrC2.p, mrC2.sig, nrow = 1, ncol = 3, widths = c(1.25, 1), common.legend = TRUE, legend = "bottom") %>%
  annotate_figure(., top = text_grob("COVID-C2, EUR w/o UKB", face = "bold", size = 14))
ggsave(glue("docs/{DATE}/{model}_covidhgi2020C2v5alleurLeaveUKBB_forrest.png"), width = 12, height = 6, units = "in")
```

## MR Scatter Plots

```{r dat_scatter_plots}
## Filter MRdat to retain SNPs
mrdat <- MRdat %>%
  mutate(outcome.name = fct_recode(outcome.name,
                                   "Critical illness" = a2_pheno,
                                   Hospitalisation = b2_pheno,
                                   "Reported infection" = c2_pheno)) %>%
  filter(mr_keep == TRUE)

## Split by exposure and outcome
mrdat.ls <- mrdat %>%
  arrange(exposure, outcome) %>%
  group_by(exposure, outcome) %>%
  group_split()

# mrres <- mrdat %>%
#   mr(., method_list = c("mr_ivw_fe", "mr_weighted_median", "mr_weighted_mode", "mr_egger_regression")) %>%
#   as_tibble() %>%
#   mutate(outcome = as.character(outcome),
#          exposure = as.character(exposure)) %>%
#   arrange(outcome, exposure) %>%
#   group_by(outcome, exposure)

# res.ls <- mrres %>%
#   left_join(egger.i) %>%
#   mutate(a = ifelse(is.na(a), 0, a),
#          outcome = as.character(outcome),
#          exposure = as.character(exposure)) %>%
#   arrange(outcome, exposure) %>%
#   group_by(outcome, exposure) %>%
#   group_split()

# Generate MR result list
## Merge mr results with MR-PRESSO corrected analysis
## Merge with egger intercepts, set intercept to 0 for other methods
## Format result file
res.ls <- MR_results %>%
  filter(outliers_removed == FALSE) %>%
  bind_rows(
    mrpresso_res %>%
      filter(method == "MRPRESSO_corrected") %>%
      filter(!is.na(b)) %>%
      rename(pval = MR.pval)
  ) %>%
  arrange(exposure, outcome, method) %>%
  left_join(egger_comb %>%
              mutate(method = "MR Egger") %>%
              rename(a = egger_intercept) %>%
              select(., -Isq, -egger_se, -pval)
  ) %>%
  mutate(method = str_replace(method, "Inverse variance weighted \\(fixed effects\\)", 'IVW'),
         method = str_replace(method, "MR Egger", 'Egger'),
         method = str_replace(method, "Weighted median", 'WME'),
         method = str_replace(method, "Weighted mode", 'WMBE'),
         method = str_replace(method, "MRPRESSO_corrected", 'MRPRESSO'),
         method = fct_relevel(method, "IVW", "Egger", "WME", "WMBE", "MRPRESSO")) %>%
  mutate(a = ifelse(is.na(a), 0, a)) %>%
  group_by(exposure, outcome) %>%
  group_split()

```

```{r plot_scatter_plots}
## Hacked TwoSampleMR::mr_scatter_plot to display MRPRESSO outliers
mr_scatter_plot2 <- function(mrdat,res){
  message("Plotting Scatters: ", mrdat$exposure.name[1], " - ", mrdat$outcome.name[1])

  ## reoriante effect direction of negative exposure values
  d <- mrdat %>%
    mutate(beta.outcome = ifelse(beta.exposure < 0, beta.outcome * -1, beta.outcome),
           beta.exposure = ifelse(beta.exposure < 0, beta.exposure * -1, beta.exposure))

  ## Make scater plot
  ggplot(data = d, aes(x = beta.exposure, y = beta.outcome)) +
    geom_errorbar(aes(ymin = beta.outcome - se.outcome, ymax = beta.outcome + se.outcome),
                  colour = "grey", width = 0) +
    geom_errorbarh(aes(xmin = beta.exposure - se.exposure, xmax = beta.exposure + se.exposure),
                   colour = "grey", height = 0) +
    geom_point(aes(colour = !mrpresso_keep)) +
    scale_colour_manual(values = c("black", "#CD534CFF")) +
    new_scale_color() +
    geom_abline(data = res, aes(intercept = a, slope = b, color = method, linetype = method), show.legend = TRUE) +
    scale_color_brewer(palette = "Set1") +
    labs(x = paste("SNP effect on\n", d$exposure.name[1]),
         y = paste("SNP effect on\n", d$outcome.name[1])) +
    theme_bw() +
    theme(legend.position = "bottom",
          legend.direction = "horizontal",
          text = element_text(size=8)) +
    guides(linetype = guide_legend(nrow = 1),
           colour_new = FALSE)
}

# mr_scatter_plot(res.ls[[1]], mrdat.ls[[1]])
# mr_scatter_plot2(mrdat.ls[[1]], res.ls[[1]])

## Apply plot across all results
plots.ls <- map2(mrdat.ls, res.ls, mr_scatter_plot2)

## Combine all plots and export to pdf file
# p.out <- ggpubr::ggarrange(plotlist = plots.ls, nrow=3, ncol=2,
#                   common.legend = TRUE, legend = 'bottom')
# p.out %>%
#   ggpubr::ggexport(filename = glue("docs/{DATE}/{model}_MRScatterPlots{DATE}.pdf"),  pointsize = 8, verbose = T)

```


## MR Funnel Plots

```{r dat_funnel_plots}

# run twosample MR on each SNP individualy
res_single.ls <- mrdat.ls %>%
  map(., mr_singlesnp, all_method=c("mr_ivw_fe", "mr_weighted_median", "mr_weighted_mode", "mr_egger_regression"))

## merge single snp with snp meta data (only want MR-PRESSO really)
mrres_single.ls <- bind_rows(res_single.ls) %>%
  as_tibble() %>%
  bind_rows(
    mrpresso_res %>%
      filter(method == "MRPRESSO_corrected") %>%
      filter(!is.na(b)) %>%
      rename(p = MR.pval, SNP = method) %>%
      select(exposure, outcome, id.exposure, id.outcome, SNP, b, se, p)
  ) %>%
  bind_rows() %>%
  mutate(SNP = str_replace(SNP, "MRPRESSO_corrected", 'All - MRPRESSO_corrected'),
         method = ifelse(str_detect(SNP, "All"), SNP, NA),
         SNP = ifelse(str_detect(SNP, "All"), NA, SNP),
         method = str_replace(method, "All - Inverse variance weighted \\(fixed effects\\)", 'All - IVW'),
         method = str_replace(method, "All - MR Egger", 'All - Egger'),
         method = str_replace(method, "All - Weighted median", 'All - WME'),
         method = str_replace(method, "All - Weighted mode", 'All - WMBE'),
         method = str_replace(method, "All - MRPRESSO_corrected", 'All - MRPRESSO'),
         method = fct_relevel(method, "All - IVW", "All - Egger", "All - WME", "All - WMBE", 'All - MRPRESSO')) %>%
  arrange(exposure, outcome, SNP, method) %>%
  fill(samplesize) %>%
  left_join(., bind_rows(mrdat.ls),
              by = c("outcome", "exposure", "id.exposure", "id.outcome", "SNP"))  %>%
      group_by(exposure, outcome) %>%
      group_split()


```

```{r plot_funnel_plots}
## Hacked TwoSampleMR::mr_funnel_plot to display MRPRESSO outliers
mr_funnel_plot2 <- function(singlesnp_results)
{
  requireNamespace("ggplot2", quietly = TRUE)
  requireNamespace("plyr", quietly = TRUE)

  exposure = singlesnp_results$exposure.name[1]
  outcome = as.character(singlesnp_results$outcome.name[1])
  message("Plotting Funnels: ", exposure, " - ", outcome)

  d <- singlesnp_results %>%
    mutate(method = str_replace(method, "All - ", ""),
           method = fct_relevel(method, "IVW", "Egger", "WME", "WMBE", 'MRPRESSO'))
  out <- ggplot(subset(d, !is.na(SNP)), aes(y = 1/se, x = b, color = !mrpresso_keep)) +
    geom_point() +
    scale_colour_manual(values = c("black", "#CD534CFF")) +
    new_scale_color() +
    geom_vline(data = subset(d, !is.na(method)), aes(xintercept = b, color = method, linetype = method)) +
    scale_color_brewer(palette = "Set1") +
    theme_bw() +
    theme(legend.position = "bottom",
          legend.direction = "horizontal",
          text = element_text(size=8),
          plot.title = element_text(size=8)) +
    guides(linetype = guide_legend(nrow = 1),
           colour_new = FALSE) +
    labs(title = glue(exposure, " - ", outcome),
         y = expression(1/SE[IV]),
         x = expression(beta[IV]),
         linetype = "method")
  out
}

# mr_funnel_plot2(mrres_single.ls[[1]])

# Apply funnel plot to all result files
funnel_plots.ls <- map(mrres_single.ls, mr_funnel_plot2)

## Combine all plots and export to pdf file
# funnel_p.out <- ggpubr::ggarrange(plotlist = funnel_plots.ls, nrow=3, ncol=2,
#                            common.legend = TRUE, legend = 'bottom')
# funnel_p.out %>%
#   ggpubr::ggexport(filename = glue("docs/{DATE}/{model}_MRFunnelPlots{DATE}.pdf"),  pointsize = 8, verbose = T)

```


```{r comb_scatter_funnel}
idx <- order(c(seq_along(plots.ls), seq_along(funnel_plots.ls)))
scatter_funnel <- (c(plots.ls, funnel_plots.ls))[idx]

scatter_funnel.out <- ggpubr::ggarrange(plotlist = scatter_funnel, nrow=3, ncol=2, align = "h",
                          common.legend = TRUE, legend = 'bottom')
scatter_funnel.out %>%
  ggpubr::ggexport(filename = glue("docs/{DATE}/{model}_MRScatterFunnelPlots.pdf"),
                   pointsize = 8, verbose = T)


```
